const auctions = [
  {
    id: "1675506221",
    name: "Tommy Hilfiger jeans boy's 18-24 M",
    categories: ["Clothing", "Infants", "Bottoms"],
    currently: "7.50",
    firstBid: "7.00",
    buyPrice: "30.00",
    numberOfBids: 2,
    bids: [
      {
        bidder: {
          userID: "danobody",
          rating: 229,
          location: "Sydney",
          country: "Australia",
        },
        time: "Dec-10-01 08:21:26",
        amount: "7.25",
      },
      {
        bidder: {
          userID: "dsage39564@aol.com",
          rating: 1006,
          location: "New York",
          country: "USA",
        },
        time: "Dec-11-01 17:57:26",
        amount: "7.50",
      },
    ],
    location: "JOHNNA'S QUALITY BARGAINS",
    country: "USA",
    starts: "2001-12-10T08:21",
    ends: "Dec-15-01 22:45:26",
    status: "Pending",
    seller: {
      userID: "thewillsons-lufkin",
      rating: 117,
    },
    description:
      "A really nice pair of Tommy Hilfiger denim jeans for toddlers.",
  },
  {
    id: "1675506222",
    name: "Apple iPhone 13 Pro Max 256GB - Graphite",
    categories: ["Electronics", "Smartphones"],
    currently: "950.00",
    firstBid: "900.00",
    buyPrice: "30.00",
    numberOfBids: 4,
    bids: [
      {
        bidder: {
          userID: "techlover21",
          rating: 540,
          location: "Los Angeles",
          country: "USA",
        },
        time: "Jul-22-25 15:10:00",
        amount: "905.00",
      },
      {
        bidder: {
          userID: "bidmaster3000",
          rating: 670,
          location: "Toronto",
          country: "Canada",
        },
        time: "Jul-23-25 08:35:40",
        amount: "950.00",
      },
    ],
    location: "LA Electronics Warehouse",
    country: "USA",
    starts: "Jul-20-25 10:00:00",
    ends: "Jul-27-25 10:00:00",
    status: "Active",
    seller: {
      userID: "applefan",
      rating: 320,
    },
    description: "Brand new iPhone 13 Pro Max. Factory unlocked and sealed.",
  },
  {
    id: "1675506223",
    name: "Nintendo Switch OLED Model - White Joy-Con",
    categories: ["Gaming", "Consoles"],
    currently: "320.00",
    firstBid: "299.99",
    buyPrice: "30.00",
    numberOfBids: 3,
    bids: [],
    location: "Chicago",
    country: "USA",
    starts: "2001-12-10T08:21",
    ends: "Aug-08-25 12:00:00",
    status: "Pending",
    seller: {
      userID: "gamehub",
      rating: 610,
    },
    description: "New Nintendo Switch OLED with all accessories. Unopened box.",
  },
  {
    id: "1675506224",
    name: "Vintage Rolex Submariner Watch",
    categories: ["Accessories", "Watches", "Luxury"],
    currently: "5,200.00",
    firstBid: "4,500.00",
    buyPrice: "30.00",
    numberOfBids: 7,
    bids: [],
    location: "London",
    country: "UK",
    starts: "Jul-25-25 14:45:00",
    ends: "Aug-01-25 14:45:00",
    status: "Active",
    seller: {
      userID: "timepiece_uk",
      rating: 202,
    },
    description: "Pre-owned authentic Rolex Submariner in excellent condition.",
  },
  {
    id: "1675506225",
    name: "2020 MacBook Pro 13-inch, M1, 16GB RAM, 512GB SSD",
    categories: ["Electronics", "Laptops"],
    currently: "850.00",
    firstBid: "800.00",
    buyPrice: "30.00",
    numberOfBids: 5,
    bids: [],
    location: "Berlin",
    country: "Germany",
    starts: "Jul-28-25 09:00:00",
    ends: "Aug-04-25 09:00:00",
    status: "Pending",
    seller: {
      userID: "tech_eu",
      rating: 430,
    },
    description:
      "Gently used M1 MacBook Pro in excellent condition with original box.",
  },
  {
    id: "1675506226",
    name: "Dyson V11 Cordless Vacuum Cleaner",
    categories: ["Home", "Appliances", "Cleaning"],
    currently: "320.00",
    firstBid: "300.00",
    buyPrice: "30.00",
    numberOfBids: 3,
    bids: [],
    location: "Toronto",
    country: "Canada",
    starts: "Jul-31-25 13:00:00",
    ends: "Aug-07-25 13:00:00",
    status: "Pending",
    seller: {
      userID: "cleanliving",
      rating: 199,
    },
    description:
      "Lightweight and powerful cordless vacuum with multiple attachments.",
  },
  {
    id: "1675506227",
    name: "Adidas Ultraboost 22 - Men's Size 10",
    categories: ["Clothing", "Footwear", "Men"],
    currently: "75.00",
    firstBid: "70.00",
    buyPrice: "30.00",
    numberOfBids: 2,
    bids: [],
    location: "Melbourne",
    country: "Australia",
    starts: "Aug-02-25 10:15:00",
    ends: "Aug-09-25 10:15:00",
    status: "Pending",
    seller: {
      userID: "sneakerhead",
      rating: 315,
    },
    description: "Gently worn Adidas Ultraboost running shoes in great shape.",
  },
  {
    id: "1675506228",
    name: "Sony WH-1000XM5 Noise Cancelling Headphones",
    categories: ["Electronics", "Audio", "Headphones"],
    currently: "270.00",
    firstBid: "250.00",
    buyPrice: "30.00",
    numberOfBids: 6,
    bids: [],
    location: "Athens",
    country: "Greece",
    starts: "Aug-03-25 18:00:00",
    ends: "Aug-10-25 18:00:00",
    status: "Active",
    seller: {
      userID: "greeksounds",
      rating: 123,
    },
    description:
      "Top-tier noise cancelling headphones in pristine condition, barely used.",
  },
];

export default auctions;
